export default function getPokemonCards() {
  return [
    {
      id: 1,
      name: "Alakazam",
      number: 1,
      image: "Alakazam-Card.jpg",
      unmatched: true,
    },
    {
      id: 2,
      name: "Blastoise",
      number: 2,
      image: "Blastoise-Card.jpg",
      unmatched: true,
    },
    {
      id: 3,
      name: "Chansey",
      number: 3,
      image: "Chansey-Card.jpg",
      unmatched: true,
    },
    {
      id: 4,
      name: "Charizard",
      number: 4,
      image: "Charizard-Card.jpg",
      unmatched: true,
    },
    {
      id: 5,
      name: "Clefairy",
      number: 5,
      image: "Clefairy-Card.jpg",
      unmatched: true,
    },
    {
      id: 6,
      name: "Gyarados",
      number: 6,
      image: "Gyarados-Card.jpg",
      unmatched: true,
    },
    {
      id: 7,
      name: "Hitmonchan",
      number: 7,
      image: "Hitmonchan-Card.jpg",
      unmatched: true,
    },
    {
      id: 8,
      name: "Machamp",
      number: 8,
      image: "Machamp-Card.jpg",
      unmatched: true,
    },
    {
      id: 9,
      name: "Mewtwo",
      number: 9,
      image: "Mewtwo-Card.jpg",
      unmatched: true,
    },
    {
      id: 10,
      name: "Ninetales",
      number: 10,
      image: "Ninetales-Card.jpg",
      unmatched: true,
    },
    {
      id: 11,
      name: "Raichu",
      number: 11,
      image: "Raichu-Card.jpg",
      unmatched: true,
    },
    {
      id: 12,
      name: "Venusaur",
      number: 12,
      image: "Venusaur-Card.jpg",
      unmatched: true,
    },
    {
      id: 13,
      name: "Alakazam",
      number: 1,
      image: "Alakazam-Card.jpg",
      unmatched: true,
    },
    {
      id: 14,
      name: "Blastoise",
      number: 2,
      image: "Blastoise-Card.jpg",
      unmatched: true,
    },
    {
      id: 15,
      name: "Chansey",
      number: 3,
      image: "Chansey-Card.jpg",
      unmatched: true,
    },
    {
      id: 16,
      name: "Charizard",
      number: 4,
      image: "Charizard-Card.jpg",
      unmatched: true,
    },
    {
      id: 17,
      name: "Clefairy",
      number: 5,
      image: "Clefairy-Card.jpg",
      unmatched: true,
    },
    {
      id: 18,
      name: "Gyarados",
      number: 6,
      image: "Gyarados-Card.jpg",
      unmatched: true,
    },
    {
      id: 19,
      name: "Hitmonchan",
      number: 7,
      image: "Hitmonchan-Card.jpg",
      unmatched: true,
    },
    {
      id: 20,
      name: "Machamp",
      number: 8,
      image: "Machamp-Card.jpg",
      unmatched: true,
    },
    {
      id: 21,
      name: "Mewtwo",
      number: 9,
      image: "Mewtwo-Card.jpg",
      unmatched: true,
    },
    {
      id: 22,
      name: "Ninetales",
      number: 10,
      image: "Ninetales-Card.jpg",
      unmatched: true,
    },
    {
      id: 23,
      name: "Raichu",
      number: 11,
      image: "Raichu-Card.jpg",
      unmatched: true,
    },
    {
      id: 24,
      name: "Venusaur",
      number: 12,
      image: "Venusaur-Card.jpg",
      unmatched: true,
    },
  ];
}
